apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: nginx
          image: docker.io/tirumala18/nginx:latest
          ports:
            - containerPort: 80  
    
